BEGIN;

-- Suppression des tables
DROP TABLE IF EXISTS "task";

-- Création des tables
CREATE TABLE "task" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL
);

-- Ajout de données
INSERT INTO "task" ("name") VALUES ('Créer un fichier index.html');
INSERT INTO "task" ("name") VALUES ('Créer le HTML de base');
INSERT INTO "task" ("name") VALUES ('Créer un fichier style.css');


COMMIT;
